Apply clippy fixes across all crates and implement various other optimizations
chaosprint/glicol pull request #153
Opened 2024-04-19 20:23 UTC by itsjunetime

This is a massive PR, I know. I tried to separate it into easily-comprehensible/reviewable commits for your ease. I'd also be happy to file them as separate PRs if that would be more desireable, but may need to do some refactoring of commit order if so.

Mostly, this just applies clippy fixes and broadly applies a few other optimizations across the repo. These optimizations are:
1. Using `Iterator::collect()` instead of creating a `vec![]` and then pushing to it from an iterator. This is preferable because the `collect` implementation uses the `Iterator::size_hint`/`ExactSizedIterator::len` to pre-allocate a vec, and then pushes into that. This can simplify numerous allocations into a single one.
2. Using `copy_from_slice` instead of iterating over a slice and manually assigning each item into another slice. This is preferable because the implementation of `copy_from_slice` is simply much simpler and more optimized than what you get from iterating over. To be fair, chances are high that the compiler optimizes the iteration out into a single memcpy anyways, but that's not guaranteed.
3. Using zipped/enumerated iterators instead of ranges and indexing. This is preferable because using iterators can elide bounds checks when accessing each item, whereas direct indexing requires bounds checks, with a potential panic, each time you access an item.

There are obviously a few other minor optimizations/changes/simplifications, but these are the big ones. I'd also be happy to explain the motivation for any other changes across this PR.

As far as I know, the only change which depends on another here is that the changes in the parser file depend on upgrading pest (which happens in the workspace `Cargo.toml`, which I committed in a different PR cause I was confused), so I guess that's something to watch out for.

As far as I can tell, this PR has exactly the same functionality as before. I've also tested basic functionality with a local build of `glicol-cli` and some test files, and it seems to work just fine. Obviously I can't guarantee that, though.

The only part of this PR that I would be worried about different functionality is the sections of rs/synth/src/node/signal/points.rs which change the code previously marked as written by ChatGPT. There was a lot of manual incrementing and indexing going on there, which is generally (imo) a code smell, so I tried to refactor it to use iterators (for the improved legibility and small performance gains as stated above), and I'm pretty certain it's doing the same thing, but I am not 100% certain. A sanity check there would be appreciated.

I'm also a little bit worried about the removal of the `unsafe` code in rs/synth/src/graph.rs. As far as I can tell, the changes I made keep all invariants and functionality the same, but with unsafe code, you can never be too safe. An extra sanity check there would also be appreciated.

I hope this isn't too overwhelming! And thank you again for making this library, it's very cool! Let me know if any help is needed while you're looking over this!

2024-04-20 13:35 UTC, chaosprint commented
Can you try to run the `build.sh` in the `./rs/wasm` folder to see if it works? It cannot compile on my Mac at the moment.

2024-04-20 20:04 UTC, itsjunetime commented
That fails to build because the main crate (which is imported by the wasm crate) imports `glicol_synth` from crates.io instead of from the local path, which causes a mismatch in the hashbrown version used (since the `glicol_synth` version in crates.io doesn't have the updated version of hashbrown). I think the best way to resolve this would be to make all the crates import other members of the workspace from their local paths, instead of from crates.io. Since it wasn't set like that when I started working on this, though, I didn't want to change it.

2024-04-21 07:45 UTC, chaosprint requested changes
it looks great and I tested with all the music examples. just needs a small change on the `imp` implementation.

2024-04-21 07:45 UTC, chaosprint commented on rs/synth/src/node/signal/imp.rs
this `imp` node is not working as ` self.clock += N;` makes it increment by block length, so it only yields impulse signal when clock is 0, and misses all the rest periodic points. :)

2024-04-21 18:26 UTC, itsjunetime commented on rs/synth/src/node/signal/imp.rs
Thanks for catching that! I knew I missed something. I just pushed a PR fixing that (as well as simplifying some more logic in delayms.rs and adding another `copy_from_slice` instead of iterative assignment)

2024-04-22 05:38 UTC, chaosprint requested changes

2024-04-22 05:38 UTC, chaosprint commented on rs/synth/src/node/delay/delayms.rs
Line 49 has an error as `main_input` is not yet defined. Moving it to line 53 fixes it.
```
if !(1..=2).contains(&main_input.buffers().len()) {
                    return;
                }
```

Also I have to change the `main` to `*main` at Line 68 to compile.

2024-04-22 06:02 UTC, itsjunetime commented on rs/synth/src/node/delay/delayms.rs
Thanks for catching that again :) I must have just forgotten to run `cargo check` before pushing last time. I just fixed that in my latest commit.

2024-04-22 06:31 UTC, chaosprint approved these changes
nice! everything works now. thanks!

2024-04-22 06:31 UTC, merged